export const projects = [
  {
    title: "Speaker adaptation",
    category: "Research · Computer vision",
    description:
      "Adapting lip-reading models to new speakers from a few video frames, without gradient updates.",
    thumbnail: "./AVSRDemo.png",
    link: "./Support-Conditioned_LoRA_for_Test-Time_Speaker_Adaptation.pdf",
    hosted: false,
  },
  {
    title: "Minecraft RL",
    category: "Reinforcement learning",
    description:
      "Training agents to fight in Minecraft, with custom environments and two-agent training.",
    thumbnail: "./MinecraftRLDemo.png",
    link: "https://github.com/CashelF/rl-minecraft-pvp",
    hosted: false,
  },
  {
    title: "Mandelbrot",
    category: "Interactive · WebGL",
    description: "A fractal explorer. Zoom in; there’s always more to see.",
    image: "./MandelbrotDemo.gif",
    thumbnail: "./MandelbrotDemo.png",
    link: "https://cashel.dev/mandelbrot",
    hosted: true,
  },
  {
    title: "Tone Track",
    category: "Machine learning · Audio",
    description: "Tracking emotion in speech over time with transformer models.",
    thumbnail: "./ToneTrackDemo.png",
    link: "https://tonetrack.cashel.dev",
    hosted: true,
  },
];

export const archiveProjects = [
  {
    title: "Dermetric",
    category: "Computer vision",
    description: "An experiment in classifying skin lesions with machine learning.",
    image: "./DermetricDemo.gif",
    thumbnail: "./DermetricDemo.png",
    link: "https://cashel.dev/Dermetric",
    hosted: true,
  },
  {
    title: "Barnsley Fern",
    category: "Interactive · Fractals",
    description: "An interactive fern grown from an iterated function system.",
    thumbnail: "./BarnsleyFernDemo.png",
    link: "https://www.cashel.dev/barnsley-fern",
    hosted: true,
  },
  {
    title: "Card Archive",
    category: "Web app",
    description: "Small recurring charges to keep unused credit cards active.",
    thumbnail: "./CardArchiveDemo.png",
    link: "https://cardarchive.cashel.dev",
    hosted: true,
  },
  {
    title: "Thick Tic-Tac-Toe",
    category: "Game",
    description: "A variation on tic-tac-toe with a different set of rules.",
    thumbnail: "./ThickTTTDemo.png",
    link: "https://cashel.dev/thick-tac-toe/",
    hosted: true,
  },
  {
    title: "Book recommendations",
    category: "Reinforcement learning",
    description: "Book recommendations that learn from feedback using contextual bandits.",
    thumbnail: "./BookAppDemo.png",
    link: "https://github.com/CashelF/book-app",
    hosted: false,
  },
  {
    title: "CV lie detection",
    category: "Computer vision",
    description: "An experiment comparing video features with deception labels in trial footage.",
    thumbnail: "./LieDetectionDemo.png",
    link: "https://github.com/CashelF/cv-lie-detection",
    hosted: false,
  },
  {
    title: "Misinformation networks",
    category: "Network analysis",
    description: "Exploring Reddit communities, news credibility, and information sharing.",
    thumbnail: "./MisinfoDemo.png",
    link: "https://github.com/CashelF/misinformation-susceptibility",
    hosted: false,
  },
  {
    title: "Pindepo",
    category: "Backend systems",
    description: "A Flask API and MongoDB backend, deployed on AWS.",
    image: "./PindepoDemo.gif",
    thumbnail: "./PindepoDemo.png",
    link: "https://github.com/Infinite-Loopers/SWELabProject",
    hosted: false,
  },
  {
    title: "tan(x)",
    category: "Embedded systems · Game",
    description: "A game built for a TM4C microcontroller, including its engine and controls.",
    image: "./TanxDemo.gif",
    thumbnail: "./TanxDemo.png",
    link: "https://github.com/CashelF/tanx-game",
    hosted: false,
  },
];
